parameters:
    greader_config.class: Eor\KnlBundle\GoogleReader\Configuration
    greader_client.class: Eor\KnlBundle\GoogleReader\Client
    greader_service.class: Eor\KnlBundle\GoogleReader\ClientService
    greader_exception_listener.class: Eor\KnlBundle\GoogleReader\Listener\ExceptionListener

services:
    greader_config:
        class: %greader_config.class%
        arguments: [%greader_config.client_id%, %greader_config.email_address%, %greader_config.client_secret%, %greader_config.redirect_uri%, %greader_config.javascript_origin%]
    
    greader_client:
        class: %greader_client.class%
        arguments: [@greader_config, @security.context, @logger]
        
    greader_service:
        class: %greader_service.class%
        arguments: [@greader_client]
        
    greader_exception_listener:
        class: %greader_exception_listener.class%
        arguments: [@greader_client]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }